name: automerge
on:
  schedule:
    - cron: '0 8 * * 1-6' # Daily at 08:00 UTC, Mon-Sat
    - cron: '0 * * * 0'   # Hourly on Sunday to catch up with staggered PR-creating jobs
  workflow_dispatch:
jobs:
  automerge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.16.4"
        env:
          GITHUB_TOKEN: "${{ github.token }}"
          MERGE_METHOD: squash
          MERGE_REQUIRED_APPROVALS: "0"
          MERGE_LABELS: automerge   # label to trigger automerge
