name: Test

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download actionlint
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash) 1.6.21
        shell: bash
      - name: Check workflow files
        run: ./actionlint -color
        shell: bash

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/python-poetry-env
      - run: poetry run pre-commit run --all-files

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/python-poetry-env
        #{% raw %}
        with:
          python-version: ${{ matrix.python-version }}
        #{% endraw %}
      - name: Run pytest with coverage
        run: poetry run pytest --cov=./ --cov-report=xml

        #{% raw %}
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          slug: JoseRZapata/data-science-project-template
        #{% endraw %}
